# Generated by Django 5.1 on 2024-09-11 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('name', models.CharField(max_length=255, unique=True)),
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CustomerOrders',
            fields=[
                ('customer_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
            ],
            options={
                'verbose_name': 'Заказ покупателя',
                'verbose_name_plural': 'Заказы покупателей',
                'db_table': 'CustomerOrders',
            },
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('name', models.CharField(max_length=255, unique=True)),
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'db_table': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='TransactionTypes',
            fields=[
                ('name', models.CharField(max_length=255, unique=True)),
                ('transaction_type_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Тип транзакции',
                'verbose_name_plural': 'Типы транзакций',
                'db_table': 'TransactionTypes',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Артикул')),
                ('description', models.TextField(max_length=255, verbose_name='Описание')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('unit_of_measure', models.CharField(max_length=50, verbose_name='Единица измерения')),
                ('min_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('customer_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customerorders', verbose_name='Заказ покупателя')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заказываемый товар',
                'verbose_name_plural': 'Заказываемые товары',
                'db_table': 'OrderItems',
            },
        ),
        migrations.CreateModel(
            name='Inventories',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('location', models.CharField(max_length=255, verbose_name='Нахождение')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Запас',
                'verbose_name_plural': 'Запасы',
                'db_table': 'Inventories',
            },
        ),
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('shipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('customer_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customerorders', verbose_name='Заказ покупателя')),
            ],
            options={
                'verbose_name': 'Отгрузка',
                'verbose_name_plural': 'Отгрузки',
                'db_table': 'Shipments',
            },
        ),
        migrations.AddField(
            model_name='customerorders',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.statuses', verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='SupplyOrders',
            fields=[
                ('supply_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.products', verbose_name='Продукт')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.statuses', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ на пополнение',
                'verbose_name_plural': 'Заказы на пополнение',
                'db_table': 'SupplyOrders',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Суммарно')),
                ('customer_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customerorders', verbose_name='Заказ покупателя')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.statuses', verbose_name='Статус')),
                ('transaction_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.transactiontypes', verbose_name='Тип транзакции')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'db_table': 'Transactions',
            },
        ),
    ]
