# Generated by Django 5.1 on 2024-09-19 11:43

from django.db import migrations
from pytils.translit import slugify as pytils_slugify


def fill_slug_field(apps, schema_editor):

    Categories = apps.get_model('core', 'Categories')
    for category in Categories.objects.filter(slug__isnull=True) | Categories.objects.filter(slug=''):
        category.slug = pytils_slugify(category.name)
        category.save(update_fields=['slug'])

    TransactionTypes = apps.get_model('core', 'TransactionTypes')
    for transaction_type in TransactionTypes.objects.filter(slug__isnull=True) | TransactionTypes.objects.filter(slug=''):
        transaction_type.slug = pytils_slugify(transaction_type.name)
        transaction_type.save(update_fields=['slug'])

    Statuses = apps.get_model('core', 'Statuses')
    for status in Statuses.objects.filter(slug__isnull=True) | Statuses.objects.filter(slug=''):
        status.slug = pytils_slugify(status.name)
        status.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categories_slug_statuses_slug_transactiontypes_slug'),
    ]

    operations = [
        migrations.RunPython(fill_slug_field)
    ]
